# Use an Nginx image for serving static files
FROM nginx:alpine

# Copy built client files to Nginx's default HTML folder
COPY --from=builder /app/client/dist /usr/share/nginx/html

# Copy a custom Nginx configuration for routing
COPY ./nginx.conf /etc/nginx/nginx.conf
